all:
  hosts:
    server1:
      ansible_host: lukas-schaefer.me
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible_key
      
  children:
    myhosts:
      hosts:
        server1:
