- name: Stop Minecraft Server
  hosts: myhosts
  vars:
    server_dir: /root/Minecraft_Server/vanilla
    check_file: '{{ server_dir }}/server.log'
  tasks:
    - name: check if players are online
      ansible.builtin.shell: |
        screen -S minecraft -X stuff '/list\015' &&
        tail {{ server_dir }}/logs/latest.log | grep "There are 0 of a max of 20 players online:" &&
        echo "No players online" || echo "Players online"
      become: true
      become_user: root
      args:
        chdir: /root/Minecraft_Server/vanilla
      register: players_online
      tags:
        - skip_ansible_lint
    - name: Stop Minecraft Server
      ansible.builtin.command: screen -S minecraft -X stuff '/stop\015'
      become: true
      become_user: root
      args:
        chdir: /root/Minecraft_Server/vanilla
        creates: "{{ check_file }}"
      register: stop_minecraft_server
      tags:
        - skip_ansible_lint


- name: Start Minecraft Server
  hosts: myhosts
  vars:
    server_dir: /root/Minecraft_Server/vanilla
    check_file: '{{ server_dir }}/server.log'
  tasks:
    - name: Start Minecraft Server
      ansible.builtin.command: screen -S minecraft -d -m bash start.sh && touch {{ check_file }}
      become: true
      become_user: root
      args:
        chdir: /root/Minecraft_Server/vanilla
        creates: "{{ check_file }}"
      register: start_minecraft_server
      tags:
        - skip_ansible_lint
