- name: Update Minecraft Server
  hosts: all
  environment:
    minecraft_server_dir: Minecraft_Server
    minecraft_server_user: github_user

  tasks:
    - name: Backup the minecraft server
      ansible.builtin.command: sudo docker exec minecraft_server tar -czvf /backup/minecraft_server_backup /data
      args:
        chdir: /home/{minecraft_server_user}/{minecraft_server_dir}
      changed_when: true
    - name: Copy the new minecraft server backup to host filesystem
      ansible.builtin.command: >
        sudo docker cp minecraft_server:/backup/minecraft_server_backup
        /home/{minecraft_server_user}/{minecraft_server_dir}/backup_$(date +%Y%m%d%H%M%S).tar.gz
      args:
        chdir: /home/{minecraft_server_user}/{minecraft_server_dir}
      changed_when: true
    - name: Stop the minecraft server
      ansible.builtin.command: sudo docker compose down
      args:
        chdir: /home/{minecraft_server_user}/{minecraft_server_dir}
      changed_when: true
    - name: Start minecraft server
      ansible.builtin.command: sudo docker compose up -d
      args:
        chdir: /home/{minecraft_server_user}/{minecraft_server_dir}
      changed_when: true
